### ISSUE TITLE
freud usage may be incorrect in example

### ISSUE THREAD

**Issue by bdice** [mosdef-hub/mosdef-workflows#25]
@mattwthompson @ahy3nz I looked at the [ua-custom-element](https://github.com/mosdef-hub/mosdef-workflows/blob/master/ua-custom-element/ua_custom_element_hoomd_freud.ipynb) example and I am not sure if it is computing RDFs in the right way with freud. Here's the code snippet:

```python
for frame in hoomd_traj:
    ch3_particles = [i for i,val in enumerate(frame.particles.typeid) if 
                frame.particles.types[val]=='CH3']
    ch4_particles = [i for i,val in enumerate(frame.particles.typeid) if
                frame.particles.types[val]=='CH4']
    oh_particles = [i for i,val in enumerate(frame.particles.typeid) if
                frame.particles.types[val]=='OH']
    
    ch3_positions = np.array(frame.particles.position[ch3_particles])
    ch4_positions = np.array(frame.particles.position[ch4_particles])
    oh_positions = np.array(frame.particles.position[oh_particles])

    ch3_ch3_rdf.compute(frame, query_points=ch3_positions, reset=False)
    ch4_ch4_rdf.compute(frame, query_points=ch4_positions, reset=False)
    oh_oh_rdf.compute(frame, query_points=oh_positions, reset=False)
```

Running `rdf.compute(frame, query_points=ch3_positions, reset=False)` will compute the RDF between CH3s and _all particles in the frame_, not between CH3s and other CH3s. You would need to run `rdf.compute(system=(box, ch_positions), query_points=ch3_positions, reset=False)`. If you agree, I can make these changes in the notebook. I don't have any concept for what the reference data should look like, so I'm not sure how to validate the outcomes.

**Comment by ahy3nz** [comment]
Go for it - I have never used freud except to learn enough to hastily put together an example, so I graciously accept improvements. The desired behavior should be comparing CH3 against other CH3 particles, not CH3 against all. The sampling is short and the data will be noisy (and you're welcome to sample longer to get smoother data), but that's probably less important compared to demonstrating how various tools can work together
